### ISSUE TITLE
Add Zuul support, and allow monitoring of all services from the Registry

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-registry#99]
- [x] Add Zuul support to the Registry, so it can route requests to microservices/gateways/monoliths. The URL would be in the form `/services/{application-name}/api/management`
- [x] When #98 is done, have a full "Admin" menu, that uses an internal Zuul to access each microservice, gateway and monolith. Each "admin" entry will have a top drop-down list (like we have currently on Swagger for gateways), where the service can be selected.
- [ ] Make the "admin" menu optional on the gateways and monoliths (as they can be monitored with the Registry)

**Comment by PierreBesson** [comment]
Also we should be able to display instances metadata, that I implemented in : https://github.com/jhipster/generator-jhipster/pull/5221

I have created a mockup for some ideas I have for how to design the admin panel.

![untitled diagram](https://cloud.githubusercontent.com/assets/513471/23166675/d2f32e0c-f841-11e6-8c88-0edf11c3e9c2.png)

Of course you will also need an overview screen. Sorry I don't have time to participate, good luck to the interns working on this.

**Comment by JulienMrgrd** [comment]
I'm on the first task.

- [x] Add Zuul support to the Registry, so it can route requests to microservices/gateways/monoliths. The URL would be in the form /services/{application-name}/api/management

**Comment by jdubois** [comment]
First task is done :-)

**Comment by JulienMrgrd** [comment]
I've commit the health page. All requests concerning instances are routed correctly.
Normally, i've checked that there is no warning concerning the back and the front. As I start on Angular 2, there are probably some improvements to apply.

By default, the Registry "instance" is selected. You can launch some gateway/microservices, refresh, etc...
![capture d ecran de 2017-03-30 11-31-49](https://cloud.githubusercontent.com/assets/11616517/24498591/3980ee88-153f-11e7-882f-fbb8b0663225.png)

**Comment by PierreBesson** [comment]
@JulienMrgrd Do you force a reload when switching services ?

**Comment by JulienMrgrd** [comment]
No, but indeed, we must do it.
There is no error displayed or "down" tag actually.

**Comment by JulienMrgrd** [comment]
With this commit, we can see instances status.
And, as @PierreBesson has proposed, instances switching provoke a refresh of routes.
(and I've remove some warnings, again)

**Comment by PierreBesson** [comment]
@JulienMrgrd Also recently I added instance metadata about registered applications (version, profile, etc.). Can you display it somewhere, maybe in the main "Application" tab.

**Comment by JulienMrgrd** [comment]
It concerns this PR ? [Fix for displaying Consul instances and metadata #5170](https://github.com/jhipster/generator-jhipster/pull/5170)

I finish on the metrics page, and after I'll add this ;)

**Comment by PierreBesson** [comment]
Yes, it's this one.

**Comment by JulienMrgrd** [comment]
It's done @PierreBesson ;)

![capture d ecran de 2017-04-04 14-44-00](https://cloud.githubusercontent.com/assets/11616517/24657106/5b0cb410-1945-11e7-8ce9-deef2886cd34.png)

Just a little problem with the badge's css, I don't know why. 
Maybe an update in package.json ?

As @jdubois said about registry, when the entire Angular 2/4 migration (and this issue) will be finished, we should apply a good layer of design/UX-UI.

**Comment by PierreBesson** [comment]
@JulienMrgrd, Nice ! Don't worry about the alignment issue. It can be fixed later.

**Comment by JulienMrgrd** [comment]
Logs page OK. The last page, "configuration", is in progress...

We may have to found a solution to reduce the loading time of logs. It's a little bit slow :/

**Note** : As we work on same files, the PR #106 (by @g-boy05) should be merge before mine.

**Comment by g-boy05** [comment]
ok we look with @heronakam on this

**Comment by deepu105** [comment]
I think you can try to add infinitescroll for logs


Thanks & Regards,
Deepu

**Comment by JulienMrgrd** [comment]
About the instance selection, are you OK (@jhipster/registry-developers) with something like that ? :

![capture d ecran de 2017-04-19 12-19-21](https://cloud.githubusercontent.com/assets/11616517/25180090/f0dad7c4-250c-11e7-9f35-825baafb50bd.png)
-------------------------------------
![capture d ecran de 2017-04-19 12-19-28](https://cloud.githubusercontent.com/assets/11616517/25180091/f0dc2d5e-250c-11e7-9b0d-14bb33a40c61.png)

A Dropdown menu, with all instances grouped by application. The item is blue when you hover it (no mouse on screenshots :mouse: ).

I'm working on a typeahead/search input to reduce the number of instances (always by thinking of a registry that can visualize a hundred of instances). 
We could, for example, search by instance or app name.

**Comment by deepu105** [comment]
@JulienMrgrd yes that would be very nice. I myself didnt like our current pills/tab selector as its not salable. Please go ahead and PR it :+1:

**Comment by JulienMrgrd** [comment]
The second task of this issue is now OK with the PR #120.

- [x] When #98 is done, have a full "Admin" menu, that uses an internal Zuul to access each microservice, gateway and monolith. Each "admin" entry will have a top drop-down list (like we have currently on Swagger for gateways), where the service can be selected.

**Comment by JulienMrgrd** [comment]
The second task of this issue is now OK with the PR #120.

------------------------------------------------
- [x] Add Zuul support to the Registry, so it can route requests to microservices/gateways/monoliths. The URL would be in the form /services/{application-name}/api/management

- [x] When #98 is done, have a full "Admin" menu, that uses an internal Zuul to access each microservice, gateway and monolith. Each "admin" entry will have a top drop-down list (like we have currently on Swagger for gateways), where the service can be selected.

**Comment by PierreBesson** [comment]
@JulienMrgrd I will showing your work on the registry tomorrow during my presentation in Rennes. It's just too good ! 🎉 
Can you do a temporary branch on your fork that includes everything you've done until now. It needs to be ready for tomorrow 14h30.

**Comment by JulienMrgrd** [comment]
@PierreBesson My "monitoringServicesZuul" branch (on my fork) is up-to-date (Angular 4, zuul, routes in admin, and the dropdown).

https://github.com/JulienMrgrd/registry/tree/monitoringServicesZuul

**Comment by jdubois** [comment]
Closing as only the last point is missing, but we'll do this later (first we have a stable registry, then we remove the screens)
